### PR TITLE
this is active fork

### PR DESCRIPTION
**Pull request by wsdjeg**

### CODE REVIEW

**Comment by cdated** [comment]
I'm not completely on board with junegunn's changes.  The selling point was that it was simpler than kien's implementation, but it eventually got more complex.  Thank you for the suggestion.

**Comment by wsdjeg** [comment]
i have try with your fork,can not work in neovim

**Comment by cdated** [comment]
This repo work fine on the latest (compiled from source) version of vim.  Neovim users will have a better experience with the junegunn fork.

**Comment by wsdjeg** [comment]
thank you

**Pull request closed without merging**
